
services:
  svr9pro:
    ports: []
    restart: unless-stopped
    environment:
      NODE_ENV: production
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        MODE: production
    command: node --loader ts-node/esm src/index.mts
    networks:
      - traefik
    volumes:
      - ./database.sqlite:/app/database.sqlite

networks:
  traefik:
    external: true
