services:
  svr9pro:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
    volumes:
      - .:/app
      - /app/node_modules
      - ./database.sqlite:/app/database.sqlite
    command: node --watch src/index.mts
